# Generated by Django 4.1.1 on 2022-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murojaat',
            name='murojat',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
