# Generated by Django 4.1.1 on 2022-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_mobiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='rasm8',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
