# Generated by Django 4.1.1 on 2022-09-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='Audioss',
        ),
    ]
