# Generated by Django 4.1.1 on 2022-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_laptop_mobiles_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='malumot',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
